spring:
  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: http://otel-opentelemetry-collector:4317
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso.qapolyflix.dopolytech.fr/realms/polyflix
  kafka:
    bootstrap-servers: kafka-0.kafka-headless:9092
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true